### ISSUE TITLE
memory running full / multiple threads

### ISSUE THREAD

**Issue by tobiasconstantin** [vvvv/VL.CEF#1]
memory usage is constantly rising when loading new websites and clicking through them

**Comment by azeno** [comment]
Huch sorry, I totally overlooked this one. I just pushed a new version (`0.0.5-stride`) which renders directly into the given render targets instead of returning a texture. You'll either need access to our `VL.Stride` preview or use a vvvv gamma > `2020.2-0218` (as of the moment of writing this comment its still being built) or the `WebRenderer [Graphics.Skia.Layers]` will simply crash due to the lack of required WGL interop bindings.

If the memory issues persist in those new versions feel free to ping me.
